/* Generated by scripts/generate-content-manifest.ts — do not edit */

export type Frontmatter = {
  title: string;
  description?: string;
  date: string;
  tags?: string[];
  featured?: boolean;
  draft?: boolean;
  cover?: string;
};

export type ProjectFrontmatter = {
  title: string;
  summary: string;
  tech?: string[];
  repo?: string;
  url?: string;
  cover?: string;
  featured?: boolean;
  date?: string;
};

export type PostEntry = { slug: string; frontmatter: Frontmatter };
export type ProjectEntry = { slug: string; frontmatter: ProjectFrontmatter };

export const postEntries: PostEntry[] = [
  {
    "slug": "on-static-sites",
    "frontmatter": {
      "title": "On building a static site you actually want to write in",
      "description": "Why a small, file-based site beats a CMS for a personal blog — and how this one is wired up.",
      "date": "2026-04-25T00:00:00.000Z",
      "tags": [
        "meta",
        "tooling"
      ],
      "featured": true,
      "draft": false
    }
  },
  {
    "slug": "hello-world",
    "frontmatter": {
      "title": "Hello, world",
      "description": "First post — what this blog is and why it exists.",
      "date": "2026-04-20T00:00:00.000Z",
      "tags": [
        "meta",
        "intro"
      ],
      "featured": true,
      "draft": false
    }
  }
];

export const projectEntries: ProjectEntry[] = [
  {
    "slug": "notes-engine",
    "frontmatter": {
      "title": "Notes Engine",
      "summary": "The static site generator powering this blog. MDX + Vite + GitHub Actions.",
      "tech": [
        "vite",
        "mdx",
        "shiki",
        "react"
      ],
      "repo": "https://github.com/example/notes-engine",
      "featured": true,
      "date": "2026-03-15T00:00:00.000Z"
    }
  },
  {
    "slug": "pixel-pal",
    "frontmatter": {
      "title": "Pixel Pal",
      "summary": "A tiny pixel-art editor that runs entirely in the browser, with palette presets and PNG export.",
      "tech": [
        "typescript",
        "canvas",
        "vite"
      ],
      "repo": "https://github.com/example/pixel-pal",
      "url": "https://example.com/pixel-pal",
      "featured": true,
      "date": "2026-02-10T00:00:00.000Z"
    }
  }
];

export const hasAboutContent = true;
