import fs from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import {
  generateFallbackName,
  generateFontFace,
  getMetricsForFamily,
  readMetrics,
  resolveCategoryFallbacks,
} from "fontaine";
import { paths } from "./fonts.config";

const supportedExtensions = ["woff2", "woff", "ttf"];

type ParsedFace = {
  family: string;
  source?: string;
  properties: Record<string, string>;
};

function parseFontFaces(css: string): ParsedFace[] {
  const faces: ParsedFace[] = [];
  const ruleRe = /@font-face\s*\{([^}]*)\}/g;
  let match: RegExpExecArray | null;

  while ((match = ruleRe.exec(css)) !== null) {
    const block = match[1];
    const familyMatch = block.match(/font-family:\s*([^;]+);/);
    if (!familyMatch) continue;

    const family = familyMatch[1].trim().replace(/^["']|["']$/g, "");
    const srcMatch = block.match(/url\((["']?)([^"')]+)\1\)/);
    const properties: Record<string, string> = {};

    for (const prop of ["font-weight", "font-style", "font-stretch"] as const) {
      const propMatch = block.match(new RegExp(`${prop}:\\s*([^;]+);`));
      if (propMatch) properties[prop] = propMatch[1].trim();
    }

    faces.push({
      family,
      source: srcMatch?.[2],
      properties,
    });
  }

  return faces;
}

async function resolveMetrics(family: string, source: string | undefined) {
  const fromFamily = await getMetricsForFamily(family);
  if (fromFamily) return fromFamily;
  if (!source) return null;

  const filePath = source.startsWith("/")
    ? path.join(paths.root, "public", source.replace(/^\//, ""))
    : path.resolve(path.dirname(paths.fontsCss), source);

  return readMetrics(pathToFileURL(filePath).href);
}

async function main() {
  const fontsCss = await fs.readFile(paths.fontsCss, "utf8");
  const seen = new Set<string>();
  const blocks: string[] = [
    "/* Generated by scripts/generate-font-fallbacks.ts — do not edit */",
  ];

  for (const { family, source, properties } of parseFontFaces(fontsCss)) {
    if (!source || !supportedExtensions.some((ext) => source.endsWith(ext))) continue;

    const metrics = await resolveMetrics(family, source);
    if (!metrics) {
      console.warn(`No metrics for ${family} (${source})`);
      continue;
    }

    const familyFallbacks = resolveCategoryFallbacks({
      fontFamily: family,
      fallbacks: {},
      metrics,
    });

    const fallbackFaceName = generateFallbackName(family);

    for (const fallbackFont of familyFallbacks) {
      const fallbackMetrics = await getMetricsForFamily(fallbackFont);
      if (!fallbackMetrics) continue;

      const key = `${fallbackFaceName}|${fallbackFont}|${JSON.stringify(properties)}`;
      if (seen.has(key)) continue;
      seen.add(key);

      blocks.push(
        generateFontFace(metrics, {
          name: fallbackFaceName,
          font: fallbackFont,
          metrics: fallbackMetrics,
          ...properties,
        }).trimEnd(),
      );
    }
  }

  await fs.writeFile(paths.fallbacksCss, `${blocks.join("\n\n")}\n`);
  console.log(`Wrote ${paths.fallbacksCss} (${blocks.length - 1} fallback @font-face rule(s))`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
