import fs from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import {
  generateFallbackName,
  generateFontFace,
  getMetricsForFamily,
  readMetrics,
  resolveCategoryFallbacks,
} from "fontaine";
import { fontAssets, paths } from "./fonts.config";

async function main() {
  const seen = new Set<string>();
  const blocks: string[] = [
    "/* Generated by scripts/generate-font-fallbacks.ts — do not edit */",
  ];

  for (const asset of fontAssets) {
    // Metric-adjusted fallbacks use sans system fonts; they don't help serif display
    // text and still cause visible reflow when Fraunces loads.
    if (asset.family === "Fraunces") continue;

    for (const face of asset.faces) {
      const localPath = path.join(paths.publicFonts, face.src);
      const metrics = await readMetrics(pathToFileURL(localPath).href);
      if (!metrics) {
        console.warn(`No metrics for ${asset.family} (${face.src})`);
        continue;
      }

      const properties: Record<string, string> = {};
      if (face.weight) properties["font-weight"] = face.weight;
      properties["font-style"] = "normal";

      const familyFallbacks = resolveCategoryFallbacks({
        fontFamily: asset.family,
        fallbacks: {},
        metrics,
      });

      const fallbackFaceName = generateFallbackName(asset.family);

      for (const fallbackFont of familyFallbacks) {
        const fallbackMetrics = await getMetricsForFamily(fallbackFont);
        if (!fallbackMetrics) continue;

        const key = `${fallbackFaceName}|${fallbackFont}|${JSON.stringify(properties)}`;
        if (seen.has(key)) continue;
        seen.add(key);

        blocks.push(
          generateFontFace(metrics, {
            name: fallbackFaceName,
            font: fallbackFont,
            metrics: fallbackMetrics,
            ...properties,
          }).trimEnd(),
        );
      }
    }
  }

  await fs.writeFile(paths.fallbacksCss, `${blocks.join("\n\n")}\n`);
  console.log(`Wrote ${paths.fallbacksCss} (${blocks.length - 1} fallback @font-face rule(s))`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
