import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import matter from "gray-matter";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outPath = path.join(root, "src", "lib", "content-manifest.generated.ts");

function slugFromFilename(file: string) {
  return file.replace(/\.mdx?$/, "").replace(/^\d{4}-\d{2}-\d{2}-/, "");
}

function normalizeTag(t: unknown): string | null {
  if (typeof t !== "string") return null;
  const normalized = t.trim().toLowerCase();
  return normalized ? normalized : null;
}

async function readEntries(
  dir: string,
  skipDrafts: boolean,
  kind: "post" | "project",
) {
  const abs = path.join(root, dir);
  const files = (await fs.readdir(abs)).filter((f) => /\.mdx?$/.test(f));
  const entries: object[] = [];

  for (const file of files) {
    const raw = await fs.readFile(path.join(abs, file), "utf8");
    const { data } = matter(raw);
    if (skipDrafts && data.draft) continue;

    const slug = slugFromFilename(file);
    if (kind === "post") {
      entries.push({
        slug,
        frontmatter: {
          title: data.title ?? slug,
          description: data.description,
          date: data.date ?? "",
          tags: (Array.isArray(data.tags) ? data.tags : [])
            .map(normalizeTag)
            .filter(Boolean),
          featured: Boolean(data.featured),
          draft: Boolean(data.draft),
          cover: data.cover,
        },
      });
    } else {
      entries.push({
        slug,
        frontmatter: {
          title: data.title ?? slug,
          summary: data.summary ?? "",
          tech: (Array.isArray(data.tech) ? data.tech : [])
            .map(normalizeTag)
            .filter(Boolean),
          repo: data.repo,
          url: data.url,
          cover: data.cover,
          featured: Boolean(data.featured),
          date: data.date,
        },
      });
    }
  }

  return entries;
}

async function main() {
  const [posts, projects] = await Promise.all([
    readEntries("content/posts", true, "post"),
    readEntries("content/projects", false, "project"),
  ]);

  posts.sort(
    (a, b) =>
      +new Date((b as { frontmatter: { date: string } }).frontmatter.date) -
      +new Date((a as { frontmatter: { date: string } }).frontmatter.date),
  );

  projects.sort(
    (a, b) =>
      +new Date((b as { frontmatter: { date?: string } }).frontmatter.date || 0) -
      +new Date((a as { frontmatter: { date?: string } }).frontmatter.date || 0),
  );

  const aboutPath = path.join(root, "content", "about.mdx");
  let hasAbout = false;
  try {
    await fs.access(aboutPath);
    hasAbout = true;
  } catch {
    // optional
  }

  const source = `/* Generated by scripts/generate-content-manifest.ts — do not edit */

export type Frontmatter = {
  title: string;
  description?: string;
  date: string;
  tags?: string[];
  featured?: boolean;
  draft?: boolean;
  cover?: string;
};

export type ProjectFrontmatter = {
  title: string;
  summary: string;
  tech?: string[];
  repo?: string;
  url?: string;
  cover?: string;
  featured?: boolean;
  date?: string;
};

export type PostEntry = { slug: string; frontmatter: Frontmatter };
export type ProjectEntry = { slug: string; frontmatter: ProjectFrontmatter };

export const postEntries: PostEntry[] = ${JSON.stringify(posts, null, 2)};

export const projectEntries: ProjectEntry[] = ${JSON.stringify(projects, null, 2)};

export const hasAboutContent = ${hasAbout};
`;

  await fs.writeFile(outPath, source);
  console.log(
    `Wrote ${path.relative(root, outPath)} (${posts.length} posts, ${projects.length} projects)`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
